# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8138bbe037fe33f0e801ac2985562a558d9b954cd522a6a85734232f21f603526838347513e96fcd7f5590a88a6548e1117b3dded9b32d41f6aa1241773f3b56

test:
  secret_key_base: bfd1a5bcb649ad8a89bac58f44d1e3cb5065e5baa3d8c4d343dcb528fc1a924bf7a02db18c16cdd429a910928a8b32098aeb0e0725d234af78b471870762a1ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
